### ISSUE TITLE
**Python: book 1 chapter 3.**

### ISSUE THREAD

**Issue by bobcat13** [Langex/learning-book1#1]
Задание по 3 разделу:
- прочитать
- имплементировать программу
- коммитить в git логическими блоками
- сообщение коммитов должно быть на английском
например, "1.3: your message"

**Comment by onhan** [comment]
[done](https://github.com/onhan/guess_number.git)

**Comment by onhan** [comment]
https://github.com/onhan/guess_number.git

**Comment by Koteinik** [comment]
задача выполнена https://github.com/onhan/guess_number.git

**Comment by bobcat13** [comment]
Нужно еще раз прочитать раздел 3 при этом осознать алгоритм и код программы.
Звонок на 16:00 2018-07-31 для повторного отчета о работе программы.

**Comment by bobcat13** [comment]
bug:
you need rename input() into raw_input() for correct working on python 2.7
https://stackoverflow.com/questions/21122540/input-error-nameerror-name-is-not-defined

**Comment by onhan** [comment]
исправлено  https://github.com/onhan/guess_number.git

**Comment by bobcat13** [comment]
ok, но ты указал ссылку не на тот репозиторий
и лучше указывать ссылку на конкретный коммит
например, тут надо указать https://github.com/Langex/learning-book1/commit/7121d011e14de0ba7e3c15c6349f60feb6aaf718

**Comment by bobcat13** [comment]
Нужно еще раз прочитать раздел 3 при этом осознать алгоритм и код программы.
Звонок на 11:00 2018-08-02 для повторного отчета о работе программы.

**Comment by onhan** [comment]
https://github.com/Langex/learning-book1/commit/0068b635f45381d8531c2d66b3165886afdf4d1f

**Comment by onhan** [comment]
это я проверял)

**Comment by onhan** [comment]
upgrade program https://github.com/Langex/learning-book1/commit/cf2664e255d79fbb8d9b639a8958453dc7fc8de9

**Comment by bobcat13** [comment]
комментарий upgrade program очень общий, нужно описывать конкретно что было обновлено

**Comment by bobcat13** [comment]
задачу можно закрывать
