### ISSUE TITLE
English: words 2018-08-13.

### ISSUE THREAD

**Issue by onhan** [Langex/learning-book1#14]
import, random, hangman, pics, word, split, def, get, list, index, return, display, board, print, missed, len

**Comment by Koteinik** [comment]
import – импортировать
random – случайный
hangman – палач
pics – фото
word – слово
split – трещина
def – защита
get – получить
list – список
index – индекс
return – вернуть
display – дисплей
board – доска
print – печатать
missed – пропущенный
len - ?

**Comment by bobcat13** [comment]
len = сокращенно от length

**Comment by tessy-zu** [comment]
Good job ))
