### ISSUE TITLE
**English: words 2018-07-31.**

### ISSUE THREAD

**Issue by Koteinik** [Langex/learning-book1#2]
Нужно перевести и выучить слова:
settings, team, chapter, jump, issue, request, market, explore, square, visit, convert, edit, note, preference, assignee.

**Comment by onhan** [comment]
settings  настройки
team команда
chapter  глава
jump прыгать
issue  вопрос
request  запрос
market рынок
explore исследовать
square квадрат
visit посещение
convert конвертировать
edit редактировать
note заметка
preference предпочтение
assignee правопреемник

**Comment by tessy-zu** [comment]
Придерживайся формата "слово - слово". Так лучше воспринимается информация.
Уточняющие значения:
square - квадрат, площадь
preference - свойство (больше для нашей сферы)
assignee - ответственный за задание, уполномоченный решить проблему

**Comment by tessy-zu** [comment]
Спрошу слова за 30.07 и 31.07 в 17.30

**Comment by onhan** [comment]
settings | настройки
team | команда
chapter | глава
jump | прыгать
issue | вопрос
request | запрос
market | рынок
explore | исследовать
square | квадрат, площадь
visit | посещение
convert | конвертировать
edit | редактировать
note | заметка
preference | свойство
assignee | ответственный за задание,   уполномоченный решить проблему

**Comment by onhan** [comment]
settings - настройки
team - команда
chapter -  глава
jump - прыгать
issue - вопрос
request - запрос
market - рынок
explore - исследовать
square - квадрат, площадь
visit - посещение
convert - конвертировать
edit - редактировать
note - заметка
preference - свойство
assignee - ответственный за задание, уполномоченный решить проблему

**Comment by tessy-zu** [comment]
Повторять ВСЛУХ произношение сложных слов.

**Comment by onhan** [comment]
Ок

вт, 31 июля 2018 г. в 15:35, tessy-zu <notifications@github.com>:
