### ISSUE TITLE
**English: words 2018-07-30.**

### ISSUE THREAD

**Issue by bobcat13** [Langex/learning-book1#4]
Нужно перевести и выучить слова:
pull, sync, push, commit, repository, branch, log, merge, abort, add, create, read, guess, work, some

**Comment by onhan** [comment]
Pull-вытащить 
Sync-синхронизировать
Push-От себя
Commit-передать
Repository-хранилище
Branch-ветка
Log-журнал
Merge-соединять
Abort-выкинуть
Add-добавить
Create-Создайте
Read-читать
Guess-угадывать
Work-работа 
Some-некоторые

**Comment by bobcat13** [comment]
замечаний по переводу нет

**Comment by bobcat13** [comment]
звонок по знаниям на 14:15 2018-07-31

**Comment by tessy-zu** [comment]
synchronize - синхронизировать
Repository - хранилище
Merge - соединять
Abort - выкинуть
Guess - угадывать
Some - некоторые
повторять с транскрипцией
Звонок в 17.30

**Comment by tessy-zu** [comment]
Повторять ВСЛУХ произношение сложных слов.
