### ISSUE TITLE
**English: words 2018-08-03.**

### ISSUE THREAD

**Issue by Koteinik** [Langex/learning-book1#8]
Нужно перевести и выучить слова:
learning, title, people, project, search, after, read, guide, activity, member, comment, day, label, details, switch.

**Comment by onhan** [comment]
earning - обучение
title - название
people - люди
project - проект
search - поиск
after - после
read - чтение
guide - руководство
activity - активность
member - участник
comment - комментарий
day - день
label - ярлык
details - детали
switch - переключатель

**Comment by tessy-zu** [comment]
Good job!
